//
//  Contact.swift
//  CustomScrollInteraction
//
//  Created by Mk on 2/25/25.
//

import Foundation

struct Contact: Identifiable {
	var id: String = UUID().uuidString
	let name: String
	let email: String
}

/// This consists of random contacts, ranging from A to Z.
let dummyContacts: [Contact] = [
	Contact(name: "John Doe", email: "abc@123.com"),
	Contact(name: "Jane Smith", email: "abc@123.com"),
	Contact(name: "Alice Johnson", email: "abc@123.com"),
	Contact(name: "Bob Brown", email: "abc@123.com"),
	Contact(name: "Charlie White", email: "abc@123.com"),
	Contact(name: "David Clark", email: "abc@123.com"),
	Contact(name: "Eve Davis", email: "abc@123.com"),
	Contact(name: "Frank Miller", email: "abc@123.com"),
	Contact(name: "Grace Lee", email: "abc@123.com"),
	Contact(name: "Hank Wilson", email: "abc@123.com"),
	Contact(name: "Ivy Moore", email: "abc@123.com"),
	Contact(name: "Jack Taylor", email: "abc@123.com"),
	Contact(name: "Kathy Anderson", email: "abc@123.com"),
	Contact(name: "Louis Thomas", email: "abc@123.com"),
	Contact(name: "Mona Jackson", email: "abc@123.com"),
	Contact(name: "Nina Harris", email: "abc@123.com"),
	Contact(name: "Oscar King", email: "abc@123.com"),
	Contact(name: "Paul Scott", email: "abc@123.com"),
	Contact(name: "Quincy Adams", email: "abc@123.com"),
	Contact(name: "Rachel Parker", email: "abc@123.com"),
	Contact(name: "Sam Mitchell", email: "abc@123.com"),
	Contact(name: "Tina Garcia", email: "abc@123.com"),
	Contact(name: "Ursula Rodriguez", email: "abc@123.com"),
	Contact(name: "Victor Lee", email: "abc@123.com"),
	Contact(name: "Wendy Walker", email: "abc@123.com"),
	Contact(name: "Xander Lopez", email: "abc@123.com"),
	Contact(name: "Yara Perez", email: "abc@123.com"),
	Contact(name: "Zane Bennett", email: "abc@123.com"),
	Contact(name: "Abigail Cooper", email: "abc@123.com"),
	Contact(name: "Ben Foster", email: "abc@123.com"),
	Contact(name: "Catherine James", email: "abc@123.com"),
	Contact(name: "Dylan Simmons", email: "abc@123.com"),
	Contact(name: "Eva Roberts", email: "abc@123.com"),
	Contact(name: "Felix Gray", email: "abc@123.com"),
	Contact(name: "Georgia Miller", email: "abc@123.com"),
	Contact(name: "Holly Carter", email: "abc@123.com"),
	Contact(name: "Ian Phillips", email: "abc@123.com"),
	Contact(name: "Jasmine Bennett", email: "abc@123.com"),
	Contact(name: "Keith Walker", email: "abc@123.com"),
	Contact(name: "Lily Evans", email: "abc@123.com"),
	Contact(name: "Monica Ross", email: "abc@123.com"),
	Contact(name: "Nolan Gray", email: "abc@123.com"),
	Contact(name: "Olivia Young", email: "abc@123.com"),
	Contact(name: "Patrick Hayes", email: "abc@123.com"),
	Contact(name: "Quinn Hall", email: "abc@123.com"),
	Contact(name: "Riley Carter", email: "abc@123.com"),
	Contact(name: "Sophia Mitchell", email: "abc@123.com"),
	Contact(name: "Theo Sanchez", email: "abc@123.com"),
	Contact(name: "Ulysses Martinez", email: "abc@123.com"),
	Contact(name: "Vera Nelson", email: "abc@123.com"),
	Contact(name: "Willis Torres", email: "abc@123.com"),
	Contact(name: "Xena Foster", email: "abc@123.com"),
	Contact(name: "Yvonne King", email: "abc@123.com"),
	Contact(name: "Zoe Brooks", email: "abc@123.com"),
	Contact(name: "Aiden Bailey", email: "abc@123.com"),
	Contact(name: "Brenda Williams", email: "abc@123.com"),
	Contact(name: "Charlie Thomas", email: "abc@123.com"),
	Contact(name: "Danielle Roberts", email: "abc@123.com"),
	Contact(name: "Ethan Davis", email: "abc@123.com"),
	Contact(name: "Faith Lewis", email: "abc@123.com"),
	Contact(name: "Gabe Mitchell", email: "abc@123.com"),
	Contact(name: "Hannah Moore", email: "abc@123.com"),
	Contact(name: "Isaac Johnson", email: "abc@123.com"),
	Contact(name: "Jade Walker", email: "abc@123.com"),
	Contact(name: "Kara Evans", email: "abc@123.com"),
	Contact(name: "Liam Hill", email: "abc@123.com"),
	Contact(name: "Megan Lee", email: "abc@123.com"),
	Contact(name: "Nathan Hall", email: "abc@123.com"),
	Contact(name: "Olivia Carter", email: "abc@123.com"),
	Contact(name: "Paul Scott", email: "abc@123.com"),
	Contact(name: "Quinn Young", email: "abc@123.com"),
	Contact(name: "Rachel Brown", email: "abc@123.com"),
	Contact(name: "Samuel Gray", email: "abc@123.com"),
	Contact(name: "Tess Phillips", email: "abc@123.com"),
	Contact(name: "Ursula Ross", email: "abc@123.com"),
	Contact(name: "Vince Harris", email: "abc@123.com"),
	Contact(name: "Wesley Jones", email: "abc@123.com"),
	Contact(name: "Xander King", email: "abc@123.com"),
	Contact(name: "Yasmin Allen", email: "abc@123.com"),
	Contact(name: "Zara White", email: "abc@123.com"),
	Contact(name: "Adam Shaw", email: "abc@123.com"),
	Contact(name: "Beatrice Morris", email: "abc@123.com"),
	Contact(name: "Chris Harris", email: "abc@123.com"),
	Contact(name: "Diana Brooks", email: "abc@123.com"),
	Contact(name: "Elliot Clark", email: "abc@123.com"),
	Contact(name: "Fiona Hill", email: "abc@123.com"),
	Contact(name: "Gina White", email: "abc@123.com"),
	Contact(name: "Henry Cox", email: "abc@123.com"),
	Contact(name: "Ivy Stewart", email: "abc@123.com"),
	Contact(name: "Jackie Davis", email: "abc@123.com"),
	Contact(name: "Kevin Lewis", email: "abc@123.com")
]
